const { escapeHtml, slugify } = require('../core/html.js');

function renderWebBookPage(input) {
  const article = addHeadingAnchors(String(input.articleHtml || ''));
  const toc = buildToc(article.headings);
  const tags = renderTags(input.tags);
  const previous = input.previous ? `<a class="nav-link" href="../${escapeHtml(input.previous.slug)}/">Previous<br><strong>${escapeHtml(input.previous.title)}</strong></a>` : '<span></span>';
  const next = input.next ? `<a class="nav-link" href="../${escapeHtml(input.next.slug)}/">Next<br><strong>${escapeHtml(input.next.title)}</strong></a>` : '<span></span>';

  return `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(input.title)} - ${escapeHtml(input.siteTitle || 'YSDA Publisher')}</title>
<style>${pageCss()}</style>
</head>
<body>
<header class="site-header">
  <a class="brand" href="../../">${escapeHtml(input.siteTitle || 'YSDA Publisher')}</a>
  <span>${escapeHtml(input.visibility || 'public-safe')}</span>
</header>
<main>
  <section class="page-hero">
    <p class="eyebrow">${escapeHtml(input.sourcePath || '')}</p>
    <h1>${escapeHtml(input.title || 'Untitled')}</h1>
    <div class="meta">
      <span>Generated ${escapeHtml(formatDate(input.generatedAt))}</span>
      <span>Updated ${escapeHtml(formatDate(input.updatedAt))}</span>
      <span>${escapeHtml(String(input.readingTimeMinutes || 1))} min read</span>
    </div>
    ${tags}
  </section>
  ${toc}
  <article class="content">
${article.html}
  </article>
  <nav class="page-nav">${previous}${next}</nav>
</main>
<footer>Generated by YSDA Publisher</footer>
</body>
</html>`;
}

function renderWebBookIndex(input) {
  const pages = Array.isArray(input.pages) ? input.pages : [];
  const skipped = Array.isArray(input.skipped) ? input.skipped : [];
  const blocked = skipped.filter((item) => item.status === 'blocked').length;
  const skippedOnly = skipped.length - blocked;
  const cards = pages.map((page) => `<a class="page-card" href="${escapeHtml(page.url)}">
    <span class="source">${escapeHtml(page.sourcePath)}</span>
    <strong>${escapeHtml(page.title)}</strong>
    <p>${escapeHtml(page.summary || '')}</p>
    <span class="card-meta">${escapeHtml((page.tags || []).join(', '))}${page.readingTimeMinutes ? ` · ${escapeHtml(String(page.readingTimeMinutes))} min` : ''}</span>
  </a>`).join('\n');

  return `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(input.siteTitle || 'YSDA Publisher')}</title>
<style>${indexCss()}</style>
</head>
<body>
<main>
  <header class="index-hero">
    <p class="eyebrow">Static web book</p>
    <h1>${escapeHtml(input.siteTitle || 'YSDA Publisher')}</h1>
    <p>${escapeHtml(input.siteDescription || '')}</p>
    <div class="summary">
      <span>${pages.length} exported</span>
      <span>${skippedOnly} skipped</span>
      <span>${blocked} blocked</span>
      <span>Generated ${escapeHtml(formatDate(input.generatedAt))}</span>
    </div>
  </header>
  <section class="tools">
    <input id="filter" type="search" placeholder="Filter notes" aria-label="Filter notes">
    <a href="safety-report.html">Safety & diagnostics</a>
    <a href="publish-manifest.json">Manifest</a>
  </section>
  <section class="grid" id="pages">
    ${cards || '<p>No notes were exported.</p>'}
  </section>
</main>
<footer>Generated by YSDA Publisher</footer>
<script>
const input = document.getElementById('filter');
const cards = [...document.querySelectorAll('.page-card')];
input?.addEventListener('input', () => {
  const query = input.value.trim().toLowerCase();
  cards.forEach((card) => {
    card.hidden = query && !card.innerText.toLowerCase().includes(query);
  });
});
</script>
</body>
</html>`;
}

function renderSafetyReport(report, options = {}) {
  const pages = Array.isArray(report.pages) ? report.pages : [];
  const skipped = Array.isArray(report.skipped) ? report.skipped : [];
  const rows = skipped.map((item) => `<tr>
    <td>${escapeHtml(item.status || 'skipped')}</td>
    <td>${escapeHtml([item.title, item.sourcePath].filter(Boolean).join(' - '))}</td>
    <td>${escapeHtml((item.reasons || []).join('; '))}</td>
  </tr>`).join('\n');
  const diagnosticRows = pages.flatMap((page) => (page.diagnostics || []).map((item) => `<tr>
    <td>${escapeHtml(item.severity || 'info')}</td>
    <td>${escapeHtml(page.title || page.sourcePath || '')}</td>
    <td>${escapeHtml(item.type || 'diagnostic')}</td>
    <td>${escapeHtml(item.message || item.target || '')}</td>
  </tr>`)).join('\n');

  return `<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Safety report - ${escapeHtml(options.siteTitle || 'YSDA Publisher')}</title>
<style>${indexCss()} .table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;background:#fff;min-width:620px}th,td{border-bottom:1px solid #d8dee8;padding:10px;text-align:left;vertical-align:top}</style>
</head>
<body>
<main>
  <header class="index-hero">
    <p class="eyebrow">Safety gate</p>
    <h1>Safety report</h1>
    <p>Generated ${escapeHtml(formatDate(report.generatedAt))} from ${escapeHtml(report.sourceFolder || '')}</p>
    <div class="summary">
      <span>${pages.length} exported</span>
      <span>${skipped.filter((item) => item.status !== 'blocked').length} skipped</span>
      <span>${skipped.filter((item) => item.status === 'blocked').length} blocked</span>
    </div>
  </header>
  <p><a href="index.html">Back to index</a></p>
  <h2>Publish gate</h2>
  <div class="table-wrap">
  <table>
    <thead><tr><th>Status</th><th>Source</th><th>Reason</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="3">All scanned notes passed the safety gate.</td></tr>'}</tbody>
  </table>
  </div>
  <h2>Rendered-note diagnostics</h2>
  <div class="table-wrap">
  <table>
    <thead><tr><th>Severity</th><th>Page</th><th>Type</th><th>Message</th></tr></thead>
    <tbody>${diagnosticRows || '<tr><td colspan="4">No rendered-note diagnostics.</td></tr>'}</tbody>
  </table>
  </div>
</main>
<footer>Generated by YSDA Publisher</footer>
</body>
</html>`;
}

function addHeadingAnchors(html) {
  const used = new Map();
  const headings = [];
  const updated = String(html || '').replace(/<h([2-4])([^>]*)>([\s\S]*?)<\/h\1>/gi, (match, level, attrs, content) => {
    const text = stripTags(content).trim();
    const existing = /\sid=(["'])(.*?)\1/i.exec(attrs);
    const base = existing && existing[2] ? existing[2] : slugify(text);
    const count = existing ? 0 : (used.get(base) || 0);
    if (!existing) {
      used.set(base, count + 1);
    }
    const id = existing ? base : count ? `${base}-${count + 1}` : base;
    headings.push({ level: Number(level), text, id });
    const cleanAttrs = String(attrs || '').replace(/\sid=(["']).*?\1/i, '').trim();
    return `<h${level}${cleanAttrs ? ` ${cleanAttrs}` : ''} id="${escapeHtml(id)}">${content}</h${level}>`;
  });
  return { html: updated, headings };
}

function buildToc(headings) {
  if (!headings.length) {
    return '';
  }
  return `<nav class="toc" aria-label="Table of contents">
    <strong>Contents</strong>
    ${headings.map((heading) => `<a class="toc-l${heading.level}" href="#${escapeHtml(heading.id)}">${escapeHtml(heading.text)}</a>`).join('')}
  </nav>`;
}

function renderTags(tags) {
  const values = Array.isArray(tags) ? tags.filter(Boolean) : [];
  if (!values.length) {
    return '';
  }
  return `<div class="tags">${values.map((tag) => `<span>${escapeHtml(tag)}</span>`).join('')}</div>`;
}

function stripTags(value) {
  return String(value || '').replace(/<[^>]+>/g, '');
}

function formatDate(value) {
  if (!value) {
    return '';
  }
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return String(value);
  }
  return date.toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, ' UTC');
}

function pageCss() {
  return `
body{margin:0;background:#f5f7fb;color:#1e293b;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.site-header{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:14px 22px;border-bottom:1px solid #d8dee8;background:#fff;position:sticky;top:0;z-index:2}
.brand{font-weight:800;color:#0f172a;text-decoration:none}
main{max-width:1040px;margin:0 auto;padding:36px 22px 60px}
.page-hero{padding:20px 0 28px;border-bottom:1px solid #d8dee8}
.eyebrow,.source,.card-meta{color:#64748b;font-size:13px}
h1{font-size:clamp(30px,5vw,52px);line-height:1.08;margin:10px 0 14px;color:#0f172a;overflow-wrap:anywhere}
.meta,.tags{display:flex;flex-wrap:wrap;gap:8px 14px;color:#475569;font-size:14px}
.tags span{border:1px solid #cbd5e1;background:#fff;padding:4px 8px;border-radius:999px}
.toc{display:flex;flex-wrap:wrap;gap:8px 14px;margin:22px 0;padding:14px 0;border-bottom:1px solid #d8dee8}
.toc strong{margin-right:8px}.toc a{color:#0f766e;text-decoration:none}.toc-l3{padding-left:10px}.toc-l4{padding-left:20px}
.content{background:#fff;border:1px solid #d8dee8;border-radius:8px;padding:28px;overflow-wrap:anywhere}
.content h1,.content h2,.content h3{color:#0f172a;line-height:1.2}.content h2{margin-top:36px;padding-top:16px;border-top:1px solid #e2e8f0}
.content p,.content li{line-height:1.72}.content pre{overflow:auto;background:#111827;color:#f9fafb;padding:16px;border-radius:8px}.content code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
.content .table-wrap{overflow-x:auto;margin:18px 0}.content table{width:100%;min-width:520px;border-collapse:collapse}.content th,.content td{border:1px solid #d8dee8;padding:8px 10px;text-align:left}.content img{max-width:100%;height:auto;border-radius:6px}
.content blockquote{border-left:4px solid #94a3b8;margin:18px 0;padding:2px 0 2px 16px;color:#334155}.content hr{border:0;border-top:1px solid #d8dee8;margin:28px 0}.mermaid{background:#f8fafc!important;color:#0f172a!important;border:1px solid #d8dee8}
.callout{border-left:4px solid #0f766e;background:#ecfdf5;padding:12px 16px;margin:18px 0;border-radius:6px}.callout-title{font-weight:700}.callout-warning,.callout-caution{border-color:#d97706;background:#fffbeb}.callout-important{border-color:#7c3aed;background:#f5f3ff}.callout-tip{border-color:#16a34a;background:#f0fdf4}.callout-info{border-color:#2563eb;background:#eff6ff}
.missing-link,.missing-asset{display:inline-block;border:1px dashed #94a3b8;background:#f8fafc;color:#475569;border-radius:6px;padding:1px 6px}.missing-asset{margin:8px 0;padding:8px 10px}
.page-nav{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:22px}.nav-link{display:block;border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:14px;color:#0f766e;text-decoration:none}
footer{text-align:center;color:#64748b;padding:26px}
@media(max-width:720px){main{padding:24px 14px}.content{padding:18px}.page-nav{grid-template-columns:1fr}.site-header{align-items:flex-start;flex-direction:column}h1{font-size:clamp(28px,10vw,40px)}.toc{display:block}.toc a{display:block;margin-top:8px;padding-left:0}.callout{padding:10px 12px}}
`;
}

function indexCss() {
  return `
body{margin:0;background:#f5f7fb;color:#1e293b;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
main{max-width:1120px;margin:0 auto;padding:42px 22px 64px}
.index-hero{padding:8px 0 28px;border-bottom:1px solid #d8dee8}
.eyebrow,.source,.card-meta{color:#64748b;font-size:13px}
h1{font-size:clamp(32px,6vw,60px);line-height:1.05;margin:8px 0 14px;color:#0f172a;overflow-wrap:anywhere}
.index-hero p{max-width:760px;line-height:1.65}.summary,.tools{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.summary span,.tools a{border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:7px 10px;color:#334155;text-decoration:none}
.tools{align-items:center;margin:22px 0}.tools input{min-width:min(340px,100%);border:1px solid #cbd5e1;border-radius:8px;padding:10px 12px;font:inherit}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.page-card{display:block;background:#fff;border:1px solid #d8dee8;border-radius:8px;padding:18px;text-decoration:none;color:#1e293b;overflow-wrap:anywhere}
.page-card:hover{border-color:#0f766e}.page-card strong{display:block;color:#0f172a;font-size:18px;margin:8px 0}.page-card p{line-height:1.55;color:#475569}
footer{text-align:center;color:#64748b;padding:26px}
@media(max-width:720px){main{padding:28px 14px}.tools{align-items:stretch;flex-direction:column}.tools input{width:100%;box-sizing:border-box}.grid{grid-template-columns:1fr}h1{font-size:clamp(30px,11vw,44px)}}
`;
}

module.exports = {
  renderSafetyReport,
  renderWebBookIndex,
  renderWebBookPage,
};
